server:
  port: 8887
  
spring:
  application:
    name: msaConfig

  cloud:
    config:
      server:
        git:
          uri: https://github.com/bizui18/JPATest.git
#          if private repository
#          username: [your username]
#          password: [your password]
